version: "3.4"

services:

  cmd:
    build: .
    image: htmlpdf
    volumes:
      - .:/usr/src/app
      - ~/.fonts:/root/.fonts

  example1:
    build: .
    image: htmlpdf
    volumes:
      - .:/usr/src/app
      - ~/.fonts:/root/.fonts
    working_dir: /usr/src/app/examples
    command: ../htmlpdf.py -i CV_PL.yaml -t CV_PL.html -o CV_PL.pdf

  example2:
    build: .
    image: htmlpdf
    volumes:
      - .:/usr/src/app
      - ~/.fonts:/root/.fonts
    working_dir: /usr/src/app/examples
    command: ../htmlpdf.py -i CV_PL.yaml -i CV_star_ratings.yaml -t CV_star_ratings.html -o CV_star_ratings.pdf
